name: workFlow
run-name: ${{ github.actor }} is pushing
on:
  push:
    branches: [test, main]
  pull_request:
    branches: [main]
env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
  DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
  DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node --version
      - run: npm install --force
      - run: npm run lint
