on:
  # Compare the preceeding commit of main -> to the current commit of the main branch.
  # (Note: To compare changes between the last pushed commit to the remote main branch set `since_last_remote_commit: true`)
  push:
    branches:
      - main
    paths:
      - "content/**"
env:
 SEED_PASS: ${{secrets.SEED_PASS}}
jobs:
  build:
    runs-on: ubuntu-latest
    name: get changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      - name: Get changed or created files
        id: files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            content/**
          json: "true"
      - name: Make an array of those file/s SHAs
        id: shas
        run: |
          echo ${{steps.files.outputs.all_changed_files}}

      - name: Send a request to revalidate those files
        if: steps.files.outputs.any_modified == 'true'
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://zagy-revalidation.herokuapp.com/revalidate"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json","Authorization":"${{secrets.SEED_PASS}}"}'
          data: '{"added":"${{steps.files.outputs.added_files}}", "deleted": "${{steps.files.outputs.deleted_files}}", "modified": "${{steps.files.outputs.modified_files}}", "renamed": "${{steps.files.outputs.renamed_files}}"}'